fix(ci): add the Helm Chart version validation

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -36,6 +36,13 @@ jobs:
           npx semantic-release --dry-run | tee release_output.txt
           echo "NEW_VERSION=$(grep -oP '(?<=The next release version is )\S+' release_output.txt)" >> $GITHUB_ENV
 
+      # Fail if the NEW_VERSION is empty
+      - name: Ensure non empty Helm Chart version
+        if: ${{ env.NEW_VERSION }} == ""
+        run: |
+          echo "Error. The Helm Chart version cannot be empty."
+          exit 1
+
       # Update Chart.yaml with the new version
       - name: Update Helm Chart version
         run: |
